### ISSUE TITLE
Change puzzle win probability

### ISSUE THREAD

**Issue by cameron-martin** [cameron-martin/tsumego#65]
#15 picks puzzles with 50% chance of solving. We must come up with a way of setting this probability to something different.

The following properties must hold:

* The probability of the user solving puzzles given to them should be a fixed value. This arises from the notion that "puzzles should be of the correct difficulty" by just defining difficulty as the probability of the user solving a puzzle.
* Every puzzle should have a non-zero probability of being shown to a user. This ensures that all puzzles will eventually get some games, and therefore have an opportunity to be rated.
* Users should not be shown the same puzzle "too often". This is a bit of vague requirement currently.
* The probability of a puzzle being chosen only depends on the rating and rating deviation.

Let ![](https://latex.codecogs.com/gif.latex?%5Cinline%20p%28Pu%20%3D%20Pu_i%29%20%3D%20f%28r_i%2C%20RD_i%29) be the probability that puzzle _i_ is shown to the user. This is the distribution that we must sample from when showing the user a puzzle, but currently I do not know how to compute this distribution.

Let ![](https://latex.codecogs.com/svg.latex?%5Cinline%20p%28w%29) be the probability that the user wins. We want this to be a fixed value.

![](https://latex.codecogs.com/svg.latex?%5Cinline%20p%28w%20%7C%20Pu%20%3D%20Pu_i%29) is the probability that a user wins given the puzzle is puzzle _i_. This is a known value and can be computed as shown in the [glicko paper](http://www.glicko.net/glicko/glicko.pdf).

The relationship between these values is as follows:

![](https://latex.codecogs.com/svg.latex?%5Cinline%20p%28w%29%20%3D%20%5Csum%5Climits_%7Bi%7D%20p%28w%20%7C%20Pu%20%3D%20Pu_i%29%20p%28Pu%20%3D%20Pu_i%29%20%3D%20%5Csum%5Climits_%7Bi%7D%20%5Cfrac%7Bf%28r_i%2C%20RD_i%29%7D%7B1%20&plus;%2010%5E%7B-g%28%5Csqrt%7BRD_i%5E2%20&plus;%20RD%5E2%7D%29%28r%20-%20r_i%29/400%7D%7D)

**Comment by tslwn** [comment]
It should be explicit that the probability puzzle <a href="https://www.codecogs.com/eqnedit.php?latex=i" target="_blank"><img src="https://latex.codecogs.com/gif.latex?i" title="i" /></a> is shown to the user <a href="https://www.codecogs.com/eqnedit.php?latex=u" target="_blank"><img src="https://latex.codecogs.com/gif.latex?u" title="u" /></a> depends on the score and rating deviation of both the puzzle and user, i.e. that the function <a href="https://www.codecogs.com/eqnedit.php?latex=u" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f" title="f" /></a> is <a href="https://www.codecogs.com/eqnedit.php?latex=f(r_i,&space;RD_i,&space;r,&space;RD)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f(r_i,&space;RD_i,&space;r,&space;RD)" title="f(r_i, RD_i, r, RD)" /></a>.

I think the best way forward is to assert a form for <a href="https://www.codecogs.com/eqnedit.php?latex=u" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f" title="f" /></a> and optimise its parameters such that <a href="https://www.codecogs.com/eqnedit.php?latex=p(w)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?p(w)" title="p(w)" /></a> is relatively constant (within an interval?) over representative values of <a href="https://www.codecogs.com/eqnedit.php?latex=r,&space;RD" target="_blank"><img src="https://latex.codecogs.com/gif.latex?r,&space;RD" title="r, RD" /></a> and <a href="https://www.codecogs.com/eqnedit.php?latex=\{r,&space;RD\}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\{r,&space;RD\}" title="\{r, RD\}" /></a> for all <a href="https://www.codecogs.com/eqnedit.php?latex=i" target="_blank"><img src="https://latex.codecogs.com/gif.latex?i" title="i" /></a>. We may be able to source this from chess data - it seems reasonable to assume that the distribution of user/puzzle ratings and rating deviations is similar.

The obvious choice of form is polynomials of increasing degree, or, in the extreme, an [artificial neural network](https://en.wikipedia.org/wiki/Universal_approximation_theorem).

**Comment by tslwn** [comment]
Alternatively, given a value of <a href="https://www.codecogs.com/eqnedit.php?latex=p(w|P_u&space;=&space;P_{u_{i}})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?p(w|P_u&space;=&space;P_{u_{i}})" title="p(w|P_u = P_{u_{i}})" /></a> for a user and all puzzles (which we could recompute each rating period?), we could select puzzles such that the distribution of <a href="https://www.codecogs.com/eqnedit.php?latex=p(w|P_u&space;=&space;P_{u_{i}})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?p(w|P_u&space;=&space;P_{u_{i}})" title="p(w|P_u = P_{u_{i}})" /></a> is approximately a chosen bounded domain distribution on [0, 1].
